kind: Deployment
apiVersion: apps/v1
metadata:
  name: gatekeeper
  namespace: default
  labels:
    app: gatekeeper
    tier: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper
      tier: public
  template:
    metadata:
      name: gatekeeper
      labels:
        app: gatekeeper
        tier: public
    spec:
      containers:
      - name: gatekeeper
        image: impyrio/gatekeeper:${DOCKER_IMAGE_TAG}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
      volumes:
        - name: config-volume
          configMap:
            name: gatekeeper-config

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: gatekeeper-config
  namespace: default
data:
  archon.redirect.conf: |-
    if ($http_x_forwarded_proto = "http") {
      return 301 $self_uri$request_uri;
    }
    if ($host != "fountainhead.impyr.io") {
      return 302 $self_uri$request_uri;
    }

---

kind: Service
apiVersion: v1
metadata:
  name: gatekeeper
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${SSL_CERT_ARN}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: gatekeeper
    tier: public
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http